server:
  port: 8088

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file://<absolute-path-to-config-repo>
