#spring.application.name=package-service

spring:
  application:
    name: package-service

  datasource:
    url: jdbc:mysql://localhost:3306/package?useSSL=false
    username: root
    password: 1124

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
