spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173" # Single origin
              - "http://localhost:5174"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: photographer-service
          uri: lb://photographer-service
          predicates:
            - Path=/photographer/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8060
